### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/adb

### ISSUE THREAD

**Issue by babjo** [openstf/adbkit#44] opened 2016-06-21 08:43 UTC
I'm developing a tool with electron and react. i use webpack for react, es6 syntax

While creating bundle.js with webpack, i found errors. i installed adbkit with npm

ERROR in ./~/adbkit/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/adb in /Users/LCH/WebstormProjects/electron/node_modules/adbkit
@ ./~/adbkit/index.js 9:15-35

ERROR in ./~/adbkit/~/adbkit-monkey/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/monkey in /Users/LCH/WebstormProjects/electron/node_modules/adbkit/node_modules/adbkit-monkey
@ ./~/adbkit/~/adbkit-monkey/index.js 9:15-38

ERROR in ./~/adbkit/~/adbkit-logcat/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/logcat in /Users/LCH/WebstormProjects/electron/node_modules/adbkit/node_modules/adbkit-logcat
@ ./~/adbkit/~/adbkit-logcat/index.js 9:15-38

**Comment by sorccu** [comment] 2016-09-30 14:31
Closing in favor of #52.

**Closed by sorccu** 2016-09-30 14:31 UTC

**Comment by riteshzefo** [comment] 2018-09-24 12:46
@einsteinx2

Can you help me out with the config?

**Comment by einsteinx2** [comment] 2018-09-26 20:54
> @einsteinx2
> 
> Can you help me out with the config?

Sure no problem, it's really simple, just annoying since you have to do it every time you update your modules. 

Assuming you're on Mac or Linux, all you have to do is open a terminal and cd into `node_modules/adbkit` and run `ln -s lib src`. Then do the same in `node_modules/adbkit-logcat` and `node_modules/adbkit-monkey`. If you're on windows, I have no idea if a Windows shortcut will work so you may need to just rename the `lib` folder to `src` or just make a second copy called `src` in case it needs that `lib` folder for some reason.

After that, everything works fine, but it gets reset everytime yarn or npm clobbers your node_modules folder.

**Comment by DeedleFake** [comment] 2018-12-19 16:36
For more info, the problem is `index.js`, which contains

```javascript
(function() {
  var Path;

  Path = require('path');

  module.exports = (function() {
    switch (Path.extname(__filename)) {
      case '.coffee':
        return require('./src/adb');
      default:
        return require('./lib/adb');
    }
  })();

}).call(this);
```

This file has two calls to `require()` in it. Webpack doesn't know that those calls are conditional, though, and tries to follow both at compile time. This results in an attempt to require the non-existent `./src/adb`, despite the condition.

I tried to get around this by importing `adbkit/lib/adb` directly, but that doesn't work either because `adbkit` in turn requires `adbkit-monkey` and `adbkit-logcat`, and both of those have the same problem.

While it would be nice to get this fixed on adbkit's end, does anyone know of a possible workaround through Webpack's configuration? I'm not too familiar with it.

**Comment by einsteinx2** [comment] 2019-01-04 20:51
Interesting... I'm not very familiar with webpack either, so I just ended up writing a bash function to make the links for me automatically so I just run one command every time I update my dependencies. Not ideal, but at least it gets my project working. Would be great if it wasn't needed though. Have never had this problem with any other module. It seems like the simplest fix would be to just have the link in the node modules if possible, but if anyone knows a way around it with webpack that would be great.

**Comment by DeedleFake** [comment] 2019-01-04 21:49
I haven't tested it yet, but it looks like `adbkit` can fix it via [some configuration in the various `package.json`s](https://webpack.js.org/concepts/module-resolution/#module-paths).

**Comment by DeedleFake** [comment] 2019-03-05 15:36
Finally got around to testing this properly. It looks like yes, adding the line `"module": "./lib/adb"` to `package.json` and similar lines to logcat and monkey fixes it.

**Comment by bmcgary** [comment] 2019-07-15 22:08
@DeedleFake does this change need to be done on adbkit, adb-monkey and adb-logcat? I see your open PR on adbkit and adb-monkey but I don't see one on adb-logcat?

**Comment by DeedleFake** [comment] 2019-07-16 16:22
From what I remember, `adb-logcat` didn't need it because it's not written in CoffeeScript.

**Comment by huhuang03** [comment] 2019-11-04 06:47
> Finally got around to testing this properly. It looks like yes, adding the line `"module": "./lib/adb"` to `package.json` and similar lines to logcat and monkey fixes it.

I follow this and fixed.
But another error throw
```
stats.js:12 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at extend (stats.js:12)
    at stats.js:22
    at Object../node_modules/adbkit/lib/adb/sync/stats.js (stats.js:48)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object.<anonymous> (sync.js:36)
    at Object../node_modules/adbkit/lib/adb/sync.js (sync.js:384)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object../node_modules/adbkit/lib/adb/client.js (client.js:7)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object../node_modules/adbkit/lib/adb.js (adb.js:2)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Module../src/index.js (index.js:5)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object.0 (rst.js:19)
    at __webpack_require__ (bootstrap:785)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
```

I have no idea how to solve it...

**Comment by einsteinx2** [comment] 2020-01-07 14:25
We were seeing the error with all three

**Comment by huhuang03** [comment] 2020-02-25 05:27
> For more info, the problem is `index.js`, which contains
> 
> ```js
> (function() {
>   var Path;
> 
>   Path = require('path');
> 
>   module.exports = (function() {
>     switch (Path.extname(__filename)) {
>       case '.coffee':
>         return require('./src/adb');
>       default:
>         return require('./lib/adb');
>     }
>   })();
> 
> }).call(this);
> ```
> 
> This file has two calls to `require()` in it. Webpack doesn't know that those calls are conditional, though, and tries to follow both at compile time. This results in an attempt to require the non-existent `./src/adb`, despite the condition.
> 
> I tried to get around this by importing `adbkit/lib/adb` directly, but that doesn't work either because `adbkit` in turn requires `adbkit-monkey` and `adbkit-logcat`, and both of those have the same problem.
> 
> While it would be nice to get this fixed on adbkit's end, does anyone know of a possible workaround through Webpack's configuration? I'm not too familiar with it.

Yes, the real reason is this. How to fix???

**Comment by huhuang03** [comment] 2020-02-26 07:41
In my practice, this error has no effect, it's just print an error message, but the webpack handle go on. 

So you can ignore this error, and continue the rest. Just replace & to ; in package.json if need.

```
    "dev": "webpack --mode development**;** electron ."
```
