### ISSUE TITLE
Browserify with adbkit: Cannot find module './src/adb'

### ISSUE THREAD

**Issue by ddaaggeett** [openstf/adbkit#46] opened 2016-07-24 22:15 UTC
my Node script:
var adb = require("adbkit");

upon running in terminal:
browserify script.js -o bundle.js

is resulting:
Error: Cannot find module './src/adb' from '/home/[user]/app/node_modules/adbkit'
at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
at Object.oncomplete (fs.js:107:15)

I have 'adbkit' installed globally and locally in my Express app, as demonstrated by my dependencies:

"dependencies": {
"adbkit": "^2.4.1",
...
}

What is going wrong? - Why is it supposedly looking for './src/adb' from '/home/[user]/app/node_modules/adbkit' when './src/adb' doesn't even exist?

**Comment by sorccu** [comment] 2016-07-25 06:39
It's because browserify doesn't know what you're going to need, and attempts to simply take all `require()` calls from the files it touches. Our main file does some "clever" (at the time) logic based on the main file's extension to decide whether it's running in a Coffee or JS environment. Even though the requires are branched in an if, browserify doesn't realize what's going on.

Next time please format your code with triple backticks. Also, duplicate of #44.

**Closed by sorccu** 2016-07-25 06:39 UTC

**Comment by ddaaggeett** [comment] 2016-07-25 12:37
For adbkit, adbkit-monkey, and adbkit-logcat I attempted to force each of their respective index.js files to reference `./lib/adb`, `./lib/monkey`, and `./lib/logcat` as it is for the JS environment.  This doesn not do the trick.

From what I can tell by what you're saying, there is no recommended solution?  I understand this was the solution for [this](https://github.com/openstf/adbkit-apkreader/issues/2).
