### ISSUE TITLE
waitForDevice not working

### ISSUE THREAD

**Issue by valentincognito** [openstf/adbkit#97] opened 2018-07-03 10:17 UTC
It seems like the waitForDevice method is not working anymore. It throws an error like so:
Unhandled rejection FailError: Failure: 'unknown host service'

Anyone had a similar issue ?

**Comment by MathiasGilson** [comment] 2018-10-29 11:20
yep, same here !

**Comment by SreejithNS** [comment] 2018-12-01 10:57
Ya Im also facing the same problem

**Comment by jupe** [comment] 2019-01-18 11:35
same for me :/. Please could somebody fix this?

**Comment by bradyriddle** [comment] 2019-01-18 22:46
For those who are curious, the problem is pretty well summed up here: 

https://stackoverflow.com/questions/38224756/error-unknown-host-service-for-adb-wait-for-devices

TL;DR the adb server used to accept the command 'wait-for-any', but now the command has to be 'wait-for-device-any'. I'm planning on submitting a pull request when I'm done with my little project.

**Comment by jupe** [comment] 2019-01-21 05:08
@bradyriddle do you have fix already in some fork/branch so I could try it out?

**Comment by bradyriddle** [comment] 2019-01-21 05:13
I do not, but if you do an npm install and go into the node module folder and find adb-kit you can find a file called waitfordevicecommand.js. if you go in that file you'll see the 'wait-for-any' string. Just swap it out and it should work.

**Comment by sundayz** [comment] 2019-06-05 23:27
@Andychochocho `node_modules/adbkit/lib/adb/command/host-serial/waitfordevice.js` on line 17:

Change this:
`this._send("host-serial:" + serial + ":wait-for-device");`
to this:
`this._send("host-serial:" + serial + ":wait-for-any-device");`

Source: https://stackoverflow.com/questions/38224756/error-unknown-host-service-for-adb-wait-for-devices?noredirect=1&lq=1

This issue seems really simple to fix. It's a 1 liner, someone should submit a PR.

**Comment by Andychochocho** [comment] 2019-06-06 01:47
@sundayz Thank you so much!! Appreciate the help! PR has been sent 👍

**Comment by sundayz** [comment] 2019-06-06 01:55
Well done! I hope it gets merged soon.

**Closed** 2023-11-22 06:55 UTC
